data: "./data/"  # cohort .yaml files + HDF5 epochs
sfreq: 128  # sampling frequency in Hertz
duration: 1  # duration of epochs in seconds
epochs: 10  # number of epochs to extract
resolution: 32  # resolution of the brain2vec
overwrite: True  # overwrite HDF5 epochs?