data: "./data/"  # cohort .yaml files + HDF5 epochs
sfreq: 128  # sampling frequency in Hertz
duration: 1  # duration of epochs in seconds
epochs: 10  # number of epochs to extract
resolution: 32  # ignored for 3D but kept for compatibility
overwrite: True  # overwrite HDF5 epochs?
# Transform type: '2d' for topomap, '3d' for spherical harmonics
transform_type: "3d"
# Maximum harmonic degree for 3D transform (only used when transform_type is '3d')
l_max: 8
